# Generated by Django 2.2.1 on 2019-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_modify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_details',
            name='excel_record',
            field=models.FileField(upload_to='media/media/excel_files'),
        ),
    ]
